[package]
name = "mmlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
libc = "0.2"
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.0"
